In [1]:
import pandas as pd

'''
1.Create a Processed E-commerce Dataset using the three provided CSV files: Orders, Customers, and Products in the "Study Material" tab in the LMS.
2.Load the datasets using Pandas and combine the related information using merge(), while using concat() to demonstrate combining DataFrames.
3.Use apply() to create or transform useful columns, and use DateTime operations to convert the order date and extract information such as the month, day, or day of the week.
4.Organize the resulting information into a clean, meaningful DataFrame and export the final processed dataset as a CSV file.
5.Upload the notebook, the input datasets and the final processed dataset on a GitHub repository before submitting your work.
'''
# Data Concatenation

customers = pd.read_csv('Day9_Customers.csv')
products = pd.read_csv('Day9_Products.csv')
orders = pd.read_csv('Day9_Orders.csv')

In [2]:
customers

   Customer_ID   Customer_Name        City Region Membership_Type
0         C001    Aarav Sharma    Srinagar  North         Premium
1         C002       Zoya Khan       Delhi  North         Regular
2         C003     Rohan Mehta      Mumbai   West         Premium
3         C004    Ananya Singh       Jammu  North         Regular
4         C005       Kabir Ali     Lucknow  North             New
5         C006    Ishita Gupta   Bengaluru  South         Premium
6         C007    Aditya Verma        Pune   West         Regular
7         C008      Sara Ahmed   Hyderabad  South         Premium
8         C009      Arjun Nair       Kochi  South         Regular
9         C010      Mehak Bhat    Srinagar  North         Premium
10        C011   Vivaan Kapoor      Jaipur  North             New
11        C012       Aisha Mir       Delhi  North         Premium
12        C013       Rahul Das     Kolkata   East         Regular
13        C014      Sana Malik      Mumbai   West             New
14        C015     Karan Joshi  Chandigarh  North         Regular
15        C016     Hiba Sheikh    Srinagar  North         Premium
16        C017       Dev Patel   Ahmedabad   West         Premium
17        C018       Manya Rao   Bengaluru  South         Regular
18        C019       Yusuf Dar    Srinagar  North             New
19        C020     Priya Menon     Chennai  South         Premium
20        C021      Aman Kumar       Delhi  North         Regular
21        C022      Alina Shah        Pune   West             New
22        C023     Nikhil Sood  Chandigarh  North         Premium
23        C024     Maryam Khan   Hyderabad  South         Regular
24        C025    Reyansh Jain     Kolkata   East             New
25        C026     Fatima Noor    Srinagar  North         Regular
26        C027   Harsh Vardhan       Noida  North         Premium
27        C028      Inaya Khan      Mumbai   West         Regular
28        C029  Sameer Qureshi       Jammu  North             New
29        C030     Riya Kapoor   Bengaluru  South         Premium

In [3]:
products

   Product_ID             Product_Name        Category  Unit_Price       Brand
0        P001      Wireless Headphones     Electronics        1499    SoundMax
1        P002      Mechanical Keyboard     Electronics        2499      KeyPro
2        P003           Wireless Mouse     Electronics         899    TechGear
3        P004              Smart Watch     Electronics        3299     FitTech
4        P005               Power Bank     Electronics        1199    VoltPlus
5        P006                   Hoodie        Clothing        1599   UrbanWear
6        P007                   Jacket        Clothing        2499  NorthStyle
7        P008                 Sneakers        Clothing        2999      StepUp
8        P009             Coffee Maker  Home & Kitchen        3499    HomeBrew
9        P010          Electric Kettle  Home & Kitchen        1499  KitchenPro
10       P011                Air Fryer  Home & Kitchen        4999   CookSmart
11       P012             Water Bottle  Home & Kitchen         699   HydroLife
12       P013       Python Programming           Books         749   TechBooks
13       P014    Data Science Handbook           Books         899   DataPress
14       P015  Machine Learning Basics           Books         999     AIPress
15       P016            Atomic Habits           Books         599   MindReads
16       P017                 Yoga Mat          Sports         899     FitLife
17       P018                 Football          Sports         799   SportZone
18       P019              Cricket Bat          Sports        2499      BatPro
19       P020             Dumbbell Set          Sports        1999   StrongFit

In [4]:
orders

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered
...,...,...,...,...,...,...,...
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled

In [5]:
#Simple concatenation (combining tables horizontally)
combined = pd.concat([orders, customers, products], ignore_index = True)
combined

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2.0,Credit Card,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,O0002,2026-01-25,C006,P003,2.0,Debit Card,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,O0003,2026-02-26,C015,P004,1.0,Cash on Delivery,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,O0004,2026-03-04,C024,P015,3.0,Net Banking,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,O0005,2026-03-29,C025,P009,5.0,Credit Card,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,NaN,NaN,NaN,P016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Atomic Habits,Books,599.0,MindReads
166,NaN,NaN,NaN,P017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yoga Mat,Sports,899.0,FitLife
167,NaN,NaN,NaN,P018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Football,Sports,799.0,SportZone
168,NaN,NaN,NaN,P019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cricket Bat,Sports,2499.0,BatPro
169,NaN,NaN,NaN,P020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dumbbell Set,Sports,1999.0,StrongFit

In [6]:
#Left merge
left = pd.merge(orders, customers, on = 'Customer_ID', how = 'left')
left

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New
...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered,Reyansh Jain,Kolkata,East,New
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped,Yusuf Dar,Srinagar,North,New
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered,Karan Joshi,Chandigarh,North,Regular
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled,Rahul Das,Kolkata,East,Regular

In [7]:
#right merge
right = pd.merge(orders, products, on = 'Product_ID', how = 'left')
right

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Coffee Maker,Home & Kitchen,3499,HomeBrew
...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered,Electric Kettle,Home & Kitchen,1499,KitchenPro
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped,Machine Learning Basics,Books,999,AIPress
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered,Atomic Habits,Books,599,MindReads
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered,Cricket Bat,Sports,2499,BatPro
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled,Dumbbell Set,Sports,1999,StrongFit

In [8]:
# Inner merge and display based on common customer_ID and Product_ID

# merge orders and customers on 'Customer_ID'
merged1 = pd.merge(orders, customers, on = 'Customer_ID')

# merge merged1(orders,customers) and products on 'Product_ID'
merged2 = pd.merge(merged1, products, on = 'Product_ID')

# we get records where we have both Product_ID and Customer_ID
merged2

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered,Reyansh Jain,Kolkata,East,New,Electric Kettle,Home & Kitchen,1499,KitchenPro
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped,Yusuf Dar,Srinagar,North,New,Machine Learning Basics,Books,999,AIPress
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Atomic Habits,Books,599,MindReads
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered,Karan Joshi,Chandigarh,North,Regular,Cricket Bat,Sports,2499,BatPro
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled,Rahul Das,Kolkata,East,Regular,Dumbbell Set,Sports,1999,StrongFit

In [9]:
# .apply() to calculate Total_Sales
def calculate_total_sales(row):
    return row['Unit_Price'] * row['Quantity']

merged2['Total_Sales'] = merged2.apply(calculate_total_sales, axis=1)

In [10]:
# Convert 'Order_Date' to datetime objects
merged2['Order_Date'] = pd.to_datetime(merged2['Order_Date'])

In [11]:
# Extract month, day, and day of the week
merged2['Order_Month'] = merged2['Order_Date'].dt.month
merged2['Order_Day'] = merged2['Order_Date'].dt.day
merged2['Order_DayOfWeek'] = merged2['Order_Date'].dt.dayofweek

In [14]:
# Display the resulting DataFrame
display(merged2.head(20))

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Total_Sales,Order_Month,Order_Day,Order_DayOfWeek
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,4998,2,19,3
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,1798,1,25,6
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,3299,2,26,3
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress,2997,3,4,2
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,17495,3,29,6
5,O0006,2026-02-09,C003,P018,3,UPI,Delivered,Rohan Mehta,Mumbai,West,Premium,Football,Sports,799,SportZone,2397,2,9,0
6,O0007,2026-02-10,C011,P003,3,UPI,Delivered,Vivaan Kapoor,Jaipur,North,New,Wireless Mouse,Electronics,899,TechGear,2697,2,10,1
7,O0008,2026-03-27,C020,P005,4,Debit Card,Delivered,Priya Menon,Chennai,South,Premium,Power Bank,Electronics,1199,VoltPlus,4796,3,27,4
8,O0009,2026-03-13,C024,P009,2,UPI,Cancelled,Maryam Khan,Hyderabad,South,Regular,Coffee Maker,Home & Kitchen,3499,HomeBrew,6998,3,13,4
9,O0010,2026-03-05,C026,P005,2,Debit Card,Shipped,Fatima Noor,Srinagar,North,Regular,Power Bank,Electronics,1199,VoltPlus,2398,3,5,3
10,O0011,2026-01-26,C022,P020,2,Net Banking,Cancelled,Alina Shah,Pune,West,New,Dumbbell Set,Sports,1999,StrongFit,3998,1,26,0
11,O0012,2026-02-03,C017,P008,5,Credit Card,Delivered,Dev Patel,Ahmedabad,West,Premium,Sneakers,Clothing,2999,StepUp,14995,2,3,1
12,O0013,2026-03-22,C005,P009,3,Cash on Delivery,Delivered,Kabir Ali,Lucknow,North,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,10497,3,22,6
13,O0014,2026-02-20,C007,P010,4,UPI,Shipped,Aditya Verma,Pune,West,Regular,Electric Kettle,Home & Kitchen,1499,KitchenPro,5996,2,20,4
14,O0015,2026-02-16,C027,P011,3,Credit Card,Cancelled,Harsh Vardhan,Noida,North,Premium,Air Fryer,Home & Kitchen,4999,CookSmart,14997,2,16,0
15,O0016,2026-02-25,C011,P008,3,UPI,Delivered,Vivaan Kapoor,Jaipur,North,New,Sneakers,Clothing,2999,StepUp,8997,2,25,2
16,O0017,2026-02-27,C023,P011,4,Net Banking,Delivered,Nikhil Sood,Chandigarh,North,Premium,Air Fryer,Home & Kitchen,4999,CookSmart,19996,2,27,4
17,O0018,2026-01-05,C003,P011,4,Net Banking,Cancelled,Rohan Mehta,Mumbai,West,Premium,Air Fryer,Home & Kitchen,4999,CookSmart,19996,1,5,0
18,O0019,2026-03-05,C019,P017,4,Net Banking,Delivered,Yusuf Dar,Srinagar,North,New,Yoga Mat,Sports,899,FitLife,3596,3,5,3
19,O0020,2026-02-06,C010,P012,3,Credit Card,Delivered,Mehak Bhat,Srinagar,North,Premium,Water Bottle,Home & Kitchen,699,HydroLife,2097,2,6,4

In [13]:
# Export the final processed dataset as a CSV file
merged2.to_csv('processed_ecommerce_dataset.csv', index=False)
print("Processed dataset exported to 'processed_ecommerce_dataset.csv'")

Processed dataset exported to 'processed_ecommerce_dataset.csv'